# Generated by Django 4.2.1 on 2023-06-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="country",
            field=models.CharField(default="INDIA", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[
                    ("MALE", "MALE"),
                    ("FEMALE", "FEMALE"),
                    ("PREFER_NOT_TO_SAY", "PREFER_NOT_TO_SAY"),
                ],
                default="MALE",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
