# Generated by Django 4.2.1 on 2023-06-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_user_country_user_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[
                    ("Male", "MALE"),
                    ("Female", "FEMALE"),
                    ("Prefer not to say", "PREFER_NOT_TO_SAY"),
                ],
                max_length=20,
            ),
        ),
    ]
